# Code Go/Java/Python sinh bằng các rule *_proto_library bên dưới → gazelle không sinh thêm.
# gazelle:ignore

load("@protobuf//bazel:java_proto_library.bzl", "java_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@protobuf//bazel:py_proto_library.bzl", "py_proto_library")
load("@rules_go//proto:def.bzl", "go_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "segment_proto",
    srcs = ["segment.proto"],
    deps = ["//com/tm/proto/vision/catalog/v1:catalog_proto"],
)

go_proto_library(
    name = "segment_go_proto",
    importpath = "com.tm/vision/com/tm/proto/vision/segment/v1",
    proto = ":segment_proto",
    deps = ["//com/tm/proto/vision/catalog/v1:catalog_go_proto"],
)

java_proto_library(
    name = "segment_java_proto",
    deps = [":segment_proto"],
)

py_proto_library(
    name = "segment_py_proto",
    deps = [":segment_proto"],
)
